# Configure main menu and social menu
# see: https://stack.jimmycai.com/config/menu
[[main]]
identifier = "about"
name = "About"
url = "https://ryankert.cc"
weight = 2

[main.params]
icon = "user"
newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ryankert01"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "linkedin"
url = "https://www.linkedin.com/in/ryankert01/"

[social.params]
icon = "brand-linkedin"